#
# (C) Copyright 2003-2008
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2008
# Stelian Pop <stelian@popies.net>
# Lead Tech Design <www.leadtechdesign.com>
#
# (C) Copyright 2015
# Doug Goldstein <cardoe@cardoe.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	+= connect-e10.o
obj-y	+= led.o
